### ISSUE TITLE
Test failures do not report as failures

### ISSUE THREAD

**Issue by aaronjensen** [lixhq/teamcity-exunit-formatter#2] opened 2016-04-15 14:57 UTC
They report as having been finished, no exception is shown, everything looks groovy even when tests actually fail.

**Comment by ssboisen** [comment] 2016-04-15 22:32
Hi @aaronjensen 

Thanks for reporting this bug. The problem is that between Elixir [v1.1](http://elixir-lang.org/docs/v1.1/ex_unit/ExUnit.html#t:failed/0) and [v1.2](http://elixir-lang.org/docs/v1.2/ex_unit/ExUnit.html#t:failed/0) ExUnit changed the structure of the failed-type used when checking the state of a test-case after it has finished.

Due to this change the [pattern match](https://github.com/lixhq/teamcity-exunit-formatter/blob/master/lib/teamcity_exunit_formatter.ex#L36) used to match against test failures is not hit and thus the necessary teamcity test failure output is never emitted.

I believe ExUnit actually broke with semantic versioning and that is why this project stopped working in ExUnit v1.2. We should be able to specify our dependency on Elixir to "~> 1.1" which means 1.x and expect to not see any backwards incompatible changes to the public api which the failed-type is part of.

Within a week I'll release two new versions of `teamcity-exunit-formatter`, one which is compatible with "~> v1.1.0" and another which is compatible with "~> v.1.2.0". You should upgrade to the latter.

**Comment by ssboisen** [comment] 2016-04-16 07:21
HI @aaronjensen 

I just published a new version v0.3.0 to hex. This version is compatible with both Elixir v1.1 and v1.2.

If you find any other problems please submit a new issue, I will close this one.

Regards

Simon

**Closed as completed** 2016-04-16 07:22 UTC

**Comment by aaronjensen** [comment] 2016-04-18 17:48
Awesome, thanks for the quick fix. It seems to work for us!
